#!/bin/sh

# Identify and display the Ethernet interface characteristics:
# (a) Identify broadcast address
# (b) Identify all IP adresses which are part of the same subnet

ifconfig -b | grep "broadcast" | cut -d ' ' -f 6
